version: "3"
services:
  hub:
    image: selenium/hub:3.14
    #ports:
    #  - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  flight-module1:
    image: simonfinnegan/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=testng.xml
    volumes:
      - C:/Users/sfinnegan/IdeaProjects/selenium.docker/test_output:/usr/share/udemy/test-ouput
  flight-module2:
    image: simonfinnegan/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=testng.xml
    volumes:
      - C:/Users/sfinnegan/IdeaProjects/selenium.docker/test_output:/usr/share/udemy/test-ouput